---
- name: Reboot iDRAC
  hosts: idrac_server
  gather_facts: no
  tasks:
    - name: Trigger iDRAC reboot
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset"
        method: POST
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        body_format: json
        body: |
          {
            "ResetType": "GracefulRestart"
          }
        validate_certs: no
        status_code: 204
