- name: Reboot Server to Start Unattended Installation
  uri:
    url: "https://{{ ansible_host }}/redfish/v1/Systems/System.Embedded.1/Actions/ComputerSystem.Reset"
    method: POST
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    headers:
      Content-Type: application/json
    body:
      ResetType: "GracefulRestart"
    body_format: json
    validate_certs: no

# - name: Configure Timezone and Display IP
#   hosts: windows_servers
#   gather_facts: no
#   tasks:
#     - name: Set timezone to UTC-7
#       win_timezone:
#         timezone: "Mountain Standard Time"  # UTC-7
    
#     - name: Display IP Address
#       win_shell: |
#         Get-NetIPAddress | Where-Object { $_.AddressFamily -eq "IPv4" -and $_.IPAddress -notlike "169.*" } | Select-Object -ExpandProperty IPAddress
#       register: ip_result

#     - name: Show IP Address
#       debug:
#         msg: "Server IP Address: {{ ip_result.stdout_lines }}"

