- name: Check Power Status via iDRAC
  hosts: idrac_server
  tasks:  
    - name: Check Power Status
      uri:
        url: "https://{{ ansible_host }}/redfish/v1/Systems/System.Embedded.1"
        method: GET
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      register: power_status

    - name: Display Power Status
      debug:
        msg: "Current Power State: {{ power_status.json.PowerState }}"
