#ไฟล์ทดลอง Mounted ได้เเต่ยังบูตไม่ได้ iDRAC9

- name: Boot and Install OS from Mounted ISO
  hosts: idrac_servers
  gather_facts: no

  tasks:
    - name: 1️⃣ ตรวจสอบว่า ISO ถูกเมานต์แล้วหรือไม่
      uri:
        url: "https://{{ ansible_host }}/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD"
        method: GET
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: no
      register: vm_status

    - name: 2️⃣ แสดง ISO ที่เมานต์อยู่
      debug:
        msg: "ISO Mounted: {{ vm_status.json.Image if vm_status.json.Image is defined else 'No ISO Mounted' }}"

    - name: 3️⃣ เมานต์ ISO ถ้ายังไม่มี ISO เมานต์อยู่
      uri:
        url: "https://{{ ansible_host }}/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia"
        method: POST
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Content-Type: "application/json"
        body:
          Image: "{{ windows_iso_url }}"
          Inserted: true
        body_format: json
        validate_certs: no
        status_code: 204,200
      when: vm_status.json.Image is not defined or vm_status.json.Image != windows_iso_url

    - name: 4️⃣ ตั้งค่าบูตจาก Virtual Media (ISO)
      uri:
        url: "https://{{ ansible_host }}/redfish/v1/Systems/System.Embedded.1"
        method: PATCH
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Content-Type: "application/json"
        body:
          Boot:
            BootSourceOverrideTarget: "Cd"
            BootSourceOverrideMode: "UEFI"
            BootSourceOverrideEnabled: "Continuous"  # หรือ "Once" ตามความเหมาะสม
        body_format: json
        validate_certs: no
        status_code: 204,200

    - name: 5️⃣ รีบูตเซิร์ฟเวอร์เพื่อติดตั้ง OS
      uri:
        url: "https://{{ ansible_host }}/redfish/v1/Systems/System.Embedded.1/Actions/ComputerSystem.Reset"
        method: POST
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Content-Type: "application/json"
        body:
          ResetType: "ForceRestart"
        body_format: json
        validate_certs: no
        status_code: 204,200

    - name: ตรวจสอบ Boot Order
      uri:
        url: "https://{{ ansible_host }}/redfish/v1/Systems/System.Embedded.1"
        method: GET
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: no
      register: boot_status

    - debug:
        msg: "Boot Order: {{ boot_status.json.Boot.BootSourceOverrideTarget }}"


    - name: 6️⃣ รอให้เซิร์ฟเวอร์บูตเสร็จ
      pause:
        seconds: 120  # รอ 2 นาที (ปรับตามความเหมาะสม)

    # - name: 7️⃣ ถอด ISO ออกจาก Virtual Media
    #   uri:
    #     url: "https://{{ ansible_host }}/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.EjectMedia"
    #     method: POST
    #     user: "{{ ansible_user }}"
    #     password: "{{ ansible_password }}"
    #     validate_certs: no
    #     status_code: 204,200
    #   when: vm_status.json.Image is defined and vm_status.json.Image == windows_iso_url

    - name: 8️⃣ แสดงข้อความเสร็จสิ้นกระบวนการ
      debug:
        msg: "Installation process complete, ISO has been ejected."
