all:
  hosts:
    windows_vm1:
      ansible_host: 10.10.40.15
      ansible_user: Administrator
      ansible_password: P@ssw0rd
      ansible_port: 5985
      ansible_connection: winrm
      ansible_winrm_transport: basic

    windows_vm2:
      ansible_host: 10.10.40.14
      ansible_user: Administrator
      ansible_password: Aa1234!@
      ansible_port: 5985
      ansible_connection: winrm
      ansible_winrm_transport: basic

    windows_vm3:
      ansible_host: 10.10.40.23
      ansible_user: Administrator
      ansible_password: P@ssw0rd
      ansible_port: 5985
      ansible_connection: winrm
      ansible_winrm_transport: basic

    # windows_vm7:
    #   ansible_host: 10.10.40.13
    #   ansible_user: Administrator
    #   ansible_password: P@ssw0rd
    #   ansible_port: 5985
    #   ansible_connection: winrm