all:
  vars:
    file_server_ip: 10.10.40.10
    file_server_path: "/SharedISO/window_server_2019.ISO"
    file_server_user: "tawan"
    file_server_password: "1122"
    validate_certs: no

  hosts:
    idrac_servers:
      ansible_host: 10.10.40.91
      ansible_user: root
      ansible_password: calvin
      ansible_connection: local
